// <auto-generated />
using System;
using CarFleet.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarFleet.Infrastructure.Migrations
{
    [DbContext(typeof(CarFleetContext))]
    [Migration("20260531210948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("CarFleet.Infrastructure.Models.DriverModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.EngineModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HorsePower")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.FleetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fleets");
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.ToTable("Vehicles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DriverModelVehicleModel", b =>
                {
                    b.Property<int>("DriversId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VehiclesId")
                        .HasColumnType("TEXT");

                    b.HasKey("DriversId", "VehiclesId");

                    b.HasIndex("VehiclesId");

                    b.ToTable("DriverModelVehicleModel");
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.CarModel", b =>
                {
                    b.HasBaseType("CarFleet.Infrastructure.Models.VehicleModel");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsElectric")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("INTEGER");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.TruckModel", b =>
                {
                    b.HasBaseType("CarFleet.Infrastructure.Models.VehicleModel");

                    b.Property<double>("CargoCapacity")
                        .HasColumnType("REAL");

                    b.Property<bool>("HasTrailer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfAxles")
                        .HasColumnType("INTEGER");

                    b.ToTable("Trucks", (string)null);
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.EngineModel", b =>
                {
                    b.HasOne("CarFleet.Infrastructure.Models.VehicleModel", "Vehicle")
                        .WithOne("Engine")
                        .HasForeignKey("CarFleet.Infrastructure.Models.EngineModel", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.VehicleModel", b =>
                {
                    b.HasOne("CarFleet.Infrastructure.Models.FleetModel", "Fleet")
                        .WithMany("Vehicles")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("DriverModelVehicleModel", b =>
                {
                    b.HasOne("CarFleet.Infrastructure.Models.DriverModel", null)
                        .WithMany()
                        .HasForeignKey("DriversId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarFleet.Infrastructure.Models.VehicleModel", null)
                        .WithMany()
                        .HasForeignKey("VehiclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.CarModel", b =>
                {
                    b.HasOne("CarFleet.Infrastructure.Models.VehicleModel", null)
                        .WithOne()
                        .HasForeignKey("CarFleet.Infrastructure.Models.CarModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.TruckModel", b =>
                {
                    b.HasOne("CarFleet.Infrastructure.Models.VehicleModel", null)
                        .WithOne()
                        .HasForeignKey("CarFleet.Infrastructure.Models.TruckModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.FleetModel", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarFleet.Infrastructure.Models.VehicleModel", b =>
                {
                    b.Navigation("Engine")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
